FROM jupyter/datascience-notebook
MAINTAINER Loic Pauleve <loic.pauleve@lri.fr>
ENV ASCPKEY $HOME/.aspera/connect/etc/asperaweb_id_dsa.openssh
ENV PATH /opt/conda/bin:/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:$HOME/.aspera/connect/bin/:/opt/sratoolkit:/opt/STAR:/opt/samtools

USER root

##
# adapted from fredericlemoine/{star,sratoolkit,R,sam}
##

COPY zlib1g-dev_1.2.8.dfsg-2+b1_amd64.deb /tmp
RUN dpkg -i /tmp/zlib1g-dev_1.2.8.*.deb && rm /tmp/*.deb

# STAR
#RUN wget https://github.com/alexdobin/STAR/archive/2.5.1b.tar.gz -O - \

COPY 2.5.1b.tar.gz /tmp
RUN tar xzf /tmp/2.5.1b.tar.gz -C /opt/ && \
      mkdir /opt/STAR && \
        cp /opt/STAR-2.5.1b/bin/Linux_x86_64_static/* /opt/STAR/ && \
          rm -rf /opt/STAR-2.5.1b/

# sra toolkit
#RUN wget -O - http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.5.7/sratoolkit.2.5.7-ubuntu64.tar.gz \

COPY sratoolkit.2.5.7-ubuntu64.tar.gz /tmp
RUN tar xzf /tmp/sratoolkit.2.5.7-ubuntu64.tar.gz -C /opt/ \
    && mkdir /opt/sratoolkit \
    && ln -s /opt/sratoolkit.2.5.7-ubuntu64/bin/* /opt/sratoolkit/

# R+DEXSeq
COPY dexseq.patch /tmp
COPY bioconductor-dexseq-1.20.1-py27r3.3.1_1.tar.bz2 /tmp
RUN cd /opt/conda && tar xvjf /tmp/bioconductor-dexseq-1.20.1-py27r3.3.1_1.tar.bz2 && rm /tmp/*.bz2 \
    && patch -i /tmp/dexseq.patch /opt/conda/lib/R/library/DEXSeq/python_scripts/dexseq_prepare_annotation.py

# samtools
# wget -O - http://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2 \

COPY samtools-1.3.1.tar.bz2 /tmp
RUN cd /tmp && \
  tar xjf samtools-1.3.1.tar.bz2 \
  && cd samtools-1.3.1 \
  && ./configure --without-curses \
  && make \
  && mkdir /opt/samtools/ \
  && mv samtools /opt/samtools/ \
  && cd .. \
  && rm -rf samtools-*


# jupyter related installs
RUN pip install \
    'ipyparallel' \
    && ipcluster nbextension enable\
    && chown -R $NB_USER /home/$NB_USER


COPY libbz2-dev_1.0.6-7+b3_amd64.deb /tmp
RUN dpkg -i /tmp/libbz2-dev_1.0.6-7+b3_amd64.deb \
	&& pip2 install htseq

USER $NB_USER

#RUN cd $HOME \
#    && wget -O - http://download.asperasoft.com/download/sw/connect/3.6.2/aspera-connect-3.6.2.117442-linux-64.tar.gz \
#    | tar xz && sh aspera-connect-3.6.2.117442-linux-64.sh \
#    && rm aspera-connect-3.6.2.117442-linux-64.tar.gz

#RUN apt-get install -q -y  wget g++ gcc make bzip2 libncurses5-dev 

